### ISSUE TITLE
Unable to open IFC Test file in the latest build of BlenderBIM

### ISSUE THREAD

**Issue by EloyRD** [myoualid/ifc-101-course#1]
Hi, while trying to follow your tutorial I got this error.
I am able to use another file without issues.

The error description in BlenderBIM is as follows.

`
Python: Traceback (most recent call last):
  File "C:\Users\Nutzer 1\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 557, in execute
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Nutzer 1\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 608, in execute
    ifc_importer.execute()
  File "C:\Users\Nutzer 1\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\import_ifc.py", line 202, in execute
    self.calculate_unit_scale()
  File "C:\Users\Nutzer 1\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\import_ifc.py", line 1079, in calculate_unit_scale
    self.unit_scale = ifcopenshell.util.unit.calculate_unit_scale(self.file)
  File "C:\Users\Nutzer 1\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\unit.py", line 435, in calculate_unit_scale
    units = file.by_type("IfcUnitAssignment")[0]
AttributeError: 'NoneType' object has no attribute 'by_type'

location: C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\bpy\ops.py:132

location: <unknown location>:-1

`

**Comment by vulevukusej** [comment]
@EloyRD are you sure you didn't mean to post this issue here: https://github.com/IfcOpenShell/IfcOpenShell/issues
